### PR TITLE
New illustrations

### PR DESCRIPTION
**Pull request by julietteTaka**
- [X] New illustration on the home page featuring a cultural heritage use case
- [X] New illustration for the contributing page
- [X] Replace carousel with a single image
- [X] Add houdini plugin link (instead of unmaintained ofxMVG)

### CODE REVIEW

**Comment by natowi** [comment]
How about adding a Blender Add-on section somewhere?

https://github.com/SBCV/Blender-Addon-Photogrammetry-Importer
https://github.com/Stwend/MeshroomTools
https://github.com/tibicen/meshroom2blender

https://github.com/cogitas3d/OrtogOnBlender
(https://www.blendernation.com/2019/07/29/meshroom-on-ortogonblender/)

**Comment by fabiencastan** [comment]
Yes, good idea!!
Have you tested them? Do you think that we should add the 4 items? Are they all usable and maintained?
Could you provide a very short summary for each tool? Just 2 small sentences to fit with the description length of the other items.

**Comment by simogasp** [comment]
https://github.com/cogitas3d/OrtogOnBlender is not really based on AliceVision.
It uses openMVG+openMVS for the 3D reconstruction

**Comment by natowi** [comment]
@simogasp Oh, yes, I did not look too close on this one. [It just mentioned MR here](https://www.blendernation.com/2019/07/29/meshroom-on-ortogonblender/)

@fabiencastan Yes, test them and check them out more thoroughly

**Comment by simogasp** [comment]
> @simogasp Oh, yes, I did not look too close on this one. [It just mentioned MR here](https://www.blendernation.com/2019/07/29/meshroom-on-ortogonblender/)

ah ok I missed that one, cool!

**Pull request merged**
